In [46]:
import cv2
import numpy

In [47]:
im_g = cv2.imread('smallgray.png',0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
img_2 = cv2.imread('smallgray.png', 1)
img_2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [49]:
cv2.imwrite('newsmallgray.png',img_2)

True

In [50]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [51]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [52]:
im_g.shape

(3, 5)

In [53]:
im_g[2,4]

182

In [54]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [55]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [56]:
img_2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [57]:
img_2[0]

array([[187, 187, 187],
       [158, 158, 158],
       [104, 104, 104],
       [121, 121, 121],
       [143, 143, 143]], dtype=uint8)

In [58]:
img_2[0,3]

array([121, 121, 121], dtype=uint8)

In [59]:
img_2[0,3,0]

121

In [60]:
img_2[0,3,0:3]

array([121, 121, 121], dtype=uint8)

In [61]:
for i in img_2.flat:
    print(i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [62]:
for i in img_2:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [63]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [68]:
ims=numpy.hstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [70]:
ims2=numpy.vstack((im_g,im_g))
ims2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [73]:
lst=numpy.hsplit(ims,5)
lst

[array([[187, 158, 104],
        [198, 125, 255],
        [209, 134, 255]], dtype=uint8), array([[121, 143, 187],
        [255, 147, 198],
        [ 97, 182, 209]], dtype=uint8), array([[158, 104, 121],
        [125, 255, 255],
        [134, 255,  97]], dtype=uint8), array([[143, 187, 158],
        [147, 198, 125],
        [182, 209, 134]], dtype=uint8), array([[104, 121, 143],
        [255, 255, 147],
        [255,  97, 182]], dtype=uint8)]

In [75]:
lst2=numpy.vsplit(ims2,3)
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]